#!/usr/local/bin/ansible-playbook --inventory=inventory
- name: 'Generate CVE Data CSV'
  hosts: localhost
  become: yes
  vars_files:
  vars:
    #ansible_python_interpreter: /usr/bin/python3
    module: "generate-cve-csv"
    cve_data_api_url: "https://access.redhat.com/hydra/rest/securitydata/cve"
    ansible_name_module: " Konductor | Provision UPI Infra | {{ module }}"

  pre_tasks:
    - name: '{{ ansible_name_module }} | load  | Login to quay container registry'
      fail:
        msg: "The variable cve_list or cve_file cannot be undefined or empty"
      when:
        - cve_file is not defined or cve_file == ''
        - cve_list is not defined or cve_list == ''
  tasks:
    - name: '{{ ansible_name_module }} | load  cve file into cve list '
      when:
        - cve_file is defined
        - not cve_file == ''
      block:
        - name: '{{ ansible_name_module }} | ensure cve_file is a valid file and exists '
          stat:
            path: "{{ cve_file }}"
          register: cve_file_check

        - name: '{{ ansible_name_module }} | load  cve_file if it exsists'
          set_fact:
            cve_list: "{{ cve_list | default([]) + [item] }}"
          loop: "{{ lookup('file', cve_file).splitlines() }}"
          register: cve_list_loaded

    - name: '{{ ansible_name_module }} | load  cve_file if it exsists'
      set_fact:
        cve_data_result_file: "/tmp/cve-data-results.csv"
      when:
        - cve_data_result_file is undefined or cve_data_result_file == ''

    - name: '{{ ansible_name_module }} | retrieve cve info '
      when:
        - cve_list is defined
        - not cve_list == ''
      block:
        - name: '{{ ansible_name_module }} | Process cve data '
          shell: >
            curl -s {{ cve_data_api_url }}/{{ item }} \
            | jq '.| {cve: .name, severity: .threat_severity, cvss_score: .cvss3.cvss3_base_score, csaw: .csaw, cwe: .cwe, details: [.details | join(";")], statement: .statement, acknowledgement: .acknowledgement, state: [.package_state[] | [ ([.product_name] | join(";")), ([.fix_state] | join(";")) , ([.package_name] | join(";")) ] | @tsv ] | join(";") }' 
          loop: "{{ cve_list }}"
          register: cve_csv_created

        - name: '{{ ansible_name_module }} | set cve data json var'
          set_fact:
            cve_data_json: "{{ cve_data_json | default([]) + [item.stdout | from_json] }}"
          loop: "{{ cve_csv_created.results }}"  
          register: cve_data_json_facts

        - name: '{{ ansible_name_module }} | set cve data lines var'
          set_fact:
            cve_data_json_clean: "{{ cve_data_json_clean | default([]) + \ 
                     [{'cve': item.cve | replace(',',' ') | quote, \
                     'severity': item.severity | replace(',',' ') | quote, \
                     'cvss_score': item.cvss_score | replace(',',' ') | quote, \
                     'csaw': item.csaw | replace(',',' ') | quote, \
                     'cwe': item.cwe | replace(',',' ') | quote, \
                     'details': item.details | join(';') | replace(',',' ') | quote, \ 
                     'statement': item.statement | replace(',',' ') | quote, \
                     'acknowledgement': item.acknowledgement | replace(',',' ') | quote, \
                     'state': item.state | replace(',',' ') | quote, \ 
                     'cve_url': cve_data_url_prefix + '/' + item.cve | quote, \
                     'rh_ridx': ((idx +2)| int | quote)
                     }] }}" 
          loop: "{{ cve_data_json }}"  
          register: cve_data_json_facts_clean

        - name: '{{ ansible_name_module }} | set cve data lines var'
          set_fact:
            cve_data_csv: "{{ cve_data_csv | default([]) \
                           + [item.cve + ',' \
                           + item.severity + ',' \
                           + item.cvss_score + ',' \
                           + item.csaw + ',' \
                           + item.cwe + ',' \
                           + item.details + ',' \
                           + item.statement + ',' \
                           + item.acknowledgement + ',' \
                           + item.state + ',' \
                           + item.cve_url + ',' \
                           + '=F' + item.rh_ridx \
                              + remediation_separator \
                              + 'G' + item.rh_ridx \
                              + remediation_separator \
                              + 'I' + item.rh_ridx
                           ] }}"
          loop: "{{  cve_data_json_clean}}"  
          register: cve_data_csv_facts

        - name: '{{ ansible_name_module }} | convert to csv '
          template:
            src: "templates/cve-date-csv.j2" 
            dest: "{{ cve_data_result_file }}"
          register: cve_tsv

