#!/usr/local/bin/ansible-playbook --inventory=inventory
- name: 'Retrieve CVE Data for RHSA TXT'
  hosts: localhost
  become: yes
  vars_files:
  vars:
    ansible_python_interpreter: /usr/bin/python3
    module: "generate-cve-txt"
    cvrf_data_api_url: "https://access.redhat.com/hydra/rest/securitydata/cvrf.json"
    cve_data_url_prefix: "https://access.redhat.com/security/cve"
    ansible_name_module: "Konductor | Provision UPI Infra | {{ module }}"

  pre_tasks:
    - name: '{{ ansible_name_module }} | Verify Required variables are correctly set '
      fail:
        msg: "The variable rhsa_list or rhsa_file cannot be undefined or empty"
      when:
        - rhsa_file is not defined or rhsa_file == ''
        - rhsa_list is not defined or rhsa_list == ''
  tasks:
    - name: '{{ ansible_name_module }} | import tasks to retrieve CVEs for RHSA'
      import_tasks: tasks/retrieve-cve-data-for-rhsa.yml

